spring:
  thymeleaf:
    prefix: classpath:static/

  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://aa1bdj11860gazf.cimrt630hwo7.ap-northeast-2.rds.amazonaws.com:3306/ebdb
    username: rds-gogumacat

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB